insert into book (title, author, description, count_of_pages) values ('MISSHA SIGNATURE EXTREME COVER CONCEALER', 'Nicol Baalham', 'error: undefined method `id'' for nil:NilClass', 1);
insert into book (title, author, description, count_of_pages) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'Artemis Loche', 'error: undefined method `id'' for nil:NilClass', 2);
insert into book (title, author, description, count_of_pages) values ('Restful Legs', 'Benjie Duddan', 'error: undefined method `id'' for nil:NilClass', 3);
insert into book (title, author, description, count_of_pages) values ('NEXIUM', 'Collin Gellier', 'error: undefined method `id'' for nil:NilClass', 4);
insert into book (title, author, description, count_of_pages) values ('Covergirl Outlast Stay Fabulous 3in1 Foundation', 'Cornelle Assandri', 'error: undefined method `id'' for nil:NilClass', 5);
insert into book (title, author, description, count_of_pages) values ('Metadate CD', 'Derril McGifford', 'error: undefined method `id'' for nil:NilClass', 6);
insert into book (title, author, description, count_of_pages) values ('Gabapentin', 'Giulia Saintsbury', 'error: undefined method `id'' for nil:NilClass', 7);
insert into book (title, author, description, count_of_pages) values ('Methocarbamol', 'Augustine Archbell', 'error: undefined method `id'' for nil:NilClass', 8);
insert into book (title, author, description, count_of_pages) values ('Chocolated Laxative', 'Joella Lundbeck', 'error: undefined method `id'' for nil:NilClass', 9);
insert into book (title, author, description, count_of_pages) values ('MBM 1 Bladder Irritated', 'Filbert Weldrake', 'error: undefined method `id'' for nil:NilClass', 10);
insert into book (title, author, description, count_of_pages) values ('RITE AID RENEWAL', 'Enoch Dunsire', 'error: undefined method `id'' for nil:NilClass', 11);
insert into book (title, author, description, count_of_pages) values ('Ear Care', 'Trixy Rawles', 'error: undefined method `id'' for nil:NilClass', 12);
insert into book (title, author, description, count_of_pages) values ('Butalbital, Acetaminophen, Caffeine, and Codeine Phosphate', 'Cesar Presman', 'error: undefined method `id'' for nil:NilClass', 13);
insert into book (title, author, description, count_of_pages) values ('Alcohol Prep Pad with Benzocaine', 'Regina Twizell', 'error: undefined method `id'' for nil:NilClass', 14);
insert into book (title, author, description, count_of_pages) values ('Jason Powersmile Anticavity ,Whitening Powerful Peppermint', 'Matthaeus Mulford', 'error: undefined method `id'' for nil:NilClass', 15);
insert into book (title, author, description, count_of_pages) values ('Azathioprine', 'Selinda Jouning', 'error: undefined method `id'' for nil:NilClass', 16);
insert into book (title, author, description, count_of_pages) values ('Tekamlo', 'Clarance Paike', 'error: undefined method `id'' for nil:NilClass', 17);
insert into book (title, author, description, count_of_pages) values ('Perphenazine', 'Marigold Simunek', 'error: undefined method `id'' for nil:NilClass', 18);
insert into book (title, author, description, count_of_pages) values ('FIBROMYALGIA RELIEF', 'Brian Normandale', 'error: undefined method `id'' for nil:NilClass', 19);
insert into book (title, author, description, count_of_pages) values ('Cataracts', 'Asher Kubiak', 'error: undefined method `id'' for nil:NilClass', 20);
insert into book (title, author, description, count_of_pages) values ('Kool and Kleen Antiseptic', 'Van Goldsby', 'error: undefined method `id'' for nil:NilClass', 21);
insert into book (title, author, description, count_of_pages) values ('nevirapine', 'Tansy Farran', 'error: undefined method `id'' for nil:NilClass', 22);
insert into book (title, author, description, count_of_pages) values ('Topamax', 'Erny Goane', 'error: undefined method `id'' for nil:NilClass', 23);
insert into book (title, author, description, count_of_pages) values ('Lyrica', 'Durant Got', 'error: undefined method `id'' for nil:NilClass', 24);
insert into book (title, author, description, count_of_pages) values ('Pollens - Weeds, Weed mix 2630', 'Chet Dybell', 'error: undefined method `id'' for nil:NilClass', 25);
insert into book (title, author, description, count_of_pages) values ('Good Sense ibuprofen', 'Hetty Kantor', 'error: undefined method `id'' for nil:NilClass', 26);
insert into book (title, author, description, count_of_pages) values ('Trazodone Hydrochloride', 'Sherwynd Ead', 'error: undefined method `id'' for nil:NilClass', 27);
insert into book (title, author, description, count_of_pages) values ('Topical 60 Sec Sodium Fluoride', 'Benn Quernel', 'error: undefined method `id'' for nil:NilClass', 28);
insert into book (title, author, description, count_of_pages) values ('Antiseptic Mouth Rinse', 'Marta Andrieux', 'error: undefined method `id'' for nil:NilClass', 29);
insert into book (title, author, description, count_of_pages) values ('Adult Low Strength Aspirin', 'Cortie Fibben', 'error: undefined method `id'' for nil:NilClass', 30);
insert into book (title, author, description, count_of_pages) values ('Ramipril', 'Bil MacAlister', 'error: undefined method `id'' for nil:NilClass', 31);
insert into book (title, author, description, count_of_pages) values ('COUMADIN', 'Rainer Belbin', 'error: undefined method `id'' for nil:NilClass', 32);
insert into book (title, author, description, count_of_pages) values ('LEG CRAMPS', 'Laryssa Durtnal', 'error: undefined method `id'' for nil:NilClass', 33);
insert into book (title, author, description, count_of_pages) values ('Divalproex Sodium', 'Kalil Del Castello', 'error: undefined method `id'' for nil:NilClass', 34);
insert into book (title, author, description, count_of_pages) values ('Lunesta', 'Rowney Vaughan-Hughes', 'error: undefined method `id'' for nil:NilClass', 35);
insert into book (title, author, description, count_of_pages) values ('2-OAK MIX, RED/WHITE POLLEN', 'Cointon Tallis', 'error: undefined method `id'' for nil:NilClass', 36);
insert into book (title, author, description, count_of_pages) values ('LBEL COULEUR LUXE AMPLIFIER XP', 'Xymenes O''Crevy', 'error: undefined method `id'' for nil:NilClass', 37);
insert into book (title, author, description, count_of_pages) values ('Methocarbamol', 'Dulcy Bromby', 'error: undefined method `id'' for nil:NilClass', 38);
insert into book (title, author, description, count_of_pages) values ('Zonisamide', 'Tally Rapi', 'error: undefined method `id'' for nil:NilClass', 39);
insert into book (title, author, description, count_of_pages) values ('Actos', 'Myrle Nozzolinii', 'error: undefined method `id'' for nil:NilClass', 40);
insert into book (title, author, description, count_of_pages) values ('BANANA BOAT', 'Nicolas Trenchard', 'error: undefined method `id'' for nil:NilClass', 41);
insert into book (title, author, description, count_of_pages) values ('ENTEX LQ', 'Chrystel Normabell', 'error: undefined method `id'' for nil:NilClass', 42);
insert into book (title, author, description, count_of_pages) values ('GAMMAGARD', 'Domenic Slavin', 'error: undefined method `id'' for nil:NilClass', 43);
insert into book (title, author, description, count_of_pages) values ('Nadolol', 'Vail Windsor', 'error: undefined method `id'' for nil:NilClass', 44);
insert into book (title, author, description, count_of_pages) values ('Noble Lion Medicated Balm', 'Ina Finders', 'error: undefined method `id'' for nil:NilClass', 45);
insert into book (title, author, description, count_of_pages) values ('natralia', 'Lesly Futter', 'error: undefined method `id'' for nil:NilClass', 46);
insert into book (title, author, description, count_of_pages) values ('Pro-Den Rx', 'Mannie Barehead', 'error: undefined method `id'' for nil:NilClass', 47);
insert into book (title, author, description, count_of_pages) values ('Health Smart Vaporizing Chest Rub', 'Malory Bucknell', 'error: undefined method `id'' for nil:NilClass', 48);
insert into book (title, author, description, count_of_pages) values ('nighttime cold flu relief', 'Heriberto Leftbridge', 'error: undefined method `id'' for nil:NilClass', 49);
insert into book (title, author, description, count_of_pages) values ('Chloroquine Phosphate', 'Robbyn Gunda', 'error: undefined method `id'' for nil:NilClass', 50);
insert into book (title, author, description, count_of_pages) values ('Benazepril Hydrochloride and Hydrochlorothiazide', 'Kelwin Hubbis', 'error: undefined method `id'' for nil:NilClass', 51);
insert into book (title, author, description, count_of_pages) values ('Naftin', 'Cris Fearnsides', 'error: undefined method `id'' for nil:NilClass', 52);
insert into book (title, author, description, count_of_pages) values ('Amoxicillin and Clavulanate Potassium', 'Zarla Duran', 'error: undefined method `id'' for nil:NilClass', 53);
insert into book (title, author, description, count_of_pages) values ('CHILDRENS DIMETAPP NIGHTTIME COLD AND CONGESTION', 'Aleece Siemons', 'error: undefined method `id'' for nil:NilClass', 54);
insert into book (title, author, description, count_of_pages) values ('Phentermine Hydrochloride', 'Erick Gonzalez', 'error: undefined method `id'' for nil:NilClass', 55);
insert into book (title, author, description, count_of_pages) values ('Daily Moisturizing', 'Sheridan Greenall', 'error: undefined method `id'' for nil:NilClass', 56);
insert into book (title, author, description, count_of_pages) values ('CHAPSTICK ULTRA SPF 30', 'Alphonso Bastian', 'error: undefined method `id'' for nil:NilClass', 57);
insert into book (title, author, description, count_of_pages) values ('Hepar Magnesium 4', 'Jillian Joriot', 'error: undefined method `id'' for nil:NilClass', 58);
insert into book (title, author, description, count_of_pages) values ('omeprazole', 'Florrie Rathke', 'error: undefined method `id'' for nil:NilClass', 59);
insert into book (title, author, description, count_of_pages) values ('Hydroxyzine Hydrochloride', 'Christa Cuss', 'error: undefined method `id'' for nil:NilClass', 60);
insert into book (title, author, description, count_of_pages) values ('Indomethacin', 'Robinette Burgum', 'error: undefined method `id'' for nil:NilClass', 61);
insert into book (title, author, description, count_of_pages) values ('Levothroid', 'Shurwood Sloegrave', 'error: undefined method `id'' for nil:NilClass', 62);
insert into book (title, author, description, count_of_pages) values ('DERMACLAIR SKIN LIGHTENING', 'Stormi Tudor', 'error: undefined method `id'' for nil:NilClass', 63);
insert into book (title, author, description, count_of_pages) values ('OMNISCAN', 'Cheri Veschambre', 'error: undefined method `id'' for nil:NilClass', 64);
insert into book (title, author, description, count_of_pages) values ('Maximum Strength Menstrual Relief', 'Hernando Bodycote', 'error: undefined method `id'' for nil:NilClass', 65);
insert into book (title, author, description, count_of_pages) values ('Zolpidem Tartrate', 'Cherise Gorse', 'error: undefined method `id'' for nil:NilClass', 66);
insert into book (title, author, description, count_of_pages) values ('LEADER Camphor Spirit', 'Elsie Munday', 'error: undefined method `id'' for nil:NilClass', 67);
insert into book (title, author, description, count_of_pages) values ('Alka-Seltzer Plus-D Multi-Symptom Sinus and Cold', 'Gregoire Simpole', 'error: undefined method `id'' for nil:NilClass', 68);
insert into book (title, author, description, count_of_pages) values ('pain reliever', 'Brendan McNickle', 'error: undefined method `id'' for nil:NilClass', 69);
insert into book (title, author, description, count_of_pages) values ('Chloroquine', 'Wilone Doogan', 'error: undefined method `id'' for nil:NilClass', 70);
insert into book (title, author, description, count_of_pages) values ('Sucralfate', 'Rakel Stollmeier', 'error: undefined method `id'' for nil:NilClass', 71);
insert into book (title, author, description, count_of_pages) values ('Colgate Sensitive Prevent and Repair', 'Dewie Luno', 'error: undefined method `id'' for nil:NilClass', 72);
insert into book (title, author, description, count_of_pages) values ('Lisinopril', 'Say McKelvey', 'error: undefined method `id'' for nil:NilClass', 73);
insert into book (title, author, description, count_of_pages) values ('Childrens Acetaminophen', 'Glendon Greenroa', 'error: undefined method `id'' for nil:NilClass', 74);
insert into book (title, author, description, count_of_pages) values ('DERMASARRA', 'Pernell Kensit', 'error: undefined method `id'' for nil:NilClass', 75);
insert into book (title, author, description, count_of_pages) values ('Quetiapine Fumarate', 'Kaylee Andersson', 'error: undefined method `id'' for nil:NilClass', 76);
insert into book (title, author, description, count_of_pages) values ('Nivea A Kiss of Protection Lip Care', 'Bartholomeus McDuffie', 'error: undefined method `id'' for nil:NilClass', 77);
insert into book (title, author, description, count_of_pages) values ('SSD', 'Kandy Brabben', 'error: undefined method `id'' for nil:NilClass', 78);
insert into book (title, author, description, count_of_pages) values ('Rough Pigweed', 'Olivier Sowerby', 'error: undefined method `id'' for nil:NilClass', 79);
insert into book (title, author, description, count_of_pages) values ('Subtilis', 'Elliott Andreone', 'error: undefined method `id'' for nil:NilClass', 80);
insert into book (title, author, description, count_of_pages) values ('Oxycodone Hydrochloride', 'Amery Corah', 'error: undefined method `id'' for nil:NilClass', 81);
insert into book (title, author, description, count_of_pages) values ('Phosphorus 8 Special Order', 'Wit Pridgeon', 'error: undefined method `id'' for nil:NilClass', 82);
insert into book (title, author, description, count_of_pages) values ('Head and Shoulders', 'Ricki Parysiak', 'error: undefined method `id'' for nil:NilClass', 83);
insert into book (title, author, description, count_of_pages) values ('Good Neighbor Pharmacy Ibuprofen Cold and Sinus', 'Blithe Chastanet', 'error: undefined method `id'' for nil:NilClass', 84);
insert into book (title, author, description, count_of_pages) values ('Pravastatin Sodium', 'Holt Dunkerly', 'error: undefined method `id'' for nil:NilClass', 85);
insert into book (title, author, description, count_of_pages) values ('Gabapentin', 'Corina Hasnney', 'error: undefined method `id'' for nil:NilClass', 86);
insert into book (title, author, description, count_of_pages) values ('Cefdinir', 'Amargo Follitt', 'error: undefined method `id'' for nil:NilClass', 87);
insert into book (title, author, description, count_of_pages) values ('Scape SPF 50 Athlete Sunblock', 'Chalmers Burnip', 'error: undefined method `id'' for nil:NilClass', 88);
insert into book (title, author, description, count_of_pages) values ('Walgreens', 'Pip Booy', 'error: undefined method `id'' for nil:NilClass', 89);
insert into book (title, author, description, count_of_pages) values ('Sun Broad Spectrum SPF 30', 'Garry Duham', 'error: undefined method `id'' for nil:NilClass', 90);
insert into book (title, author, description, count_of_pages) values ('Lancell Slimming', 'Lorenzo Kingdom', 'error: undefined method `id'' for nil:NilClass', 91);
insert into book (title, author, description, count_of_pages) values ('Dr. Scholls', 'Camella Blondell', 'error: undefined method `id'' for nil:NilClass', 92);
insert into book (title, author, description, count_of_pages) values ('CVTox', 'Edyth Philipsohn', 'error: undefined method `id'' for nil:NilClass', 93);
insert into book (title, author, description, count_of_pages) values ('Bicalutamide', 'Adoree Ropkes', 'error: undefined method `id'' for nil:NilClass', 94);
insert into book (title, author, description, count_of_pages) values ('REBETOL', 'Davidson Hillin', 'error: undefined method `id'' for nil:NilClass', 95);
insert into book (title, author, description, count_of_pages) values ('Risk True', 'Dennis Chazette', 'error: undefined method `id'' for nil:NilClass', 96);
insert into book (title, author, description, count_of_pages) values ('HYDROCODONE BITARTRATE AND ACETAMINOPHEN', 'Jerry Wastell', 'error: undefined method `id'' for nil:NilClass', 97);
insert into book (title, author, description, count_of_pages) values ('ENDOCET', 'Garrik Turton', 'error: undefined method `id'' for nil:NilClass', 98);
insert into book (title, author, description, count_of_pages) values ('Ibuprofen', 'Madel Ellwand', 'error: undefined method `id'' for nil:NilClass', 99);
insert into book (title, author, description, count_of_pages) values ('Zenzedi', 'Yance Aimeric', 'error: undefined method `id'' for nil:NilClass', 100);
